CREATE TABLE FLOSS_TYPE
AS SELECT *
FROM CSVREAD('classpath:data/flossTypes.csv');

ALTER TABLE FLOSS_TYPE ALTER COLUMN ID SET DATA TYPE BIGINT;
ALTER TABLE FLOSS_TYPE ALTER COLUMN ID SET NOT NULL;
ALTER TABLE FLOSS_TYPE ALTER COLUMN NAME SET NOT NULL;

ALTER TABLE FLOSS_TYPE
ADD PRIMARY KEY (ID);

CREATE TABLE BOBBIN_SIZE
AS SELECT *
FROM CSVREAD('classpath:data/bobbinSize.csv');

ALTER TABLE BOBBIN_SIZE ALTER COLUMN ID SET DATA TYPE BIGINT;
ALTER TABLE BOBBIN_SIZE ALTER COLUMN ID SET NOT NULL;
ALTER TABLE BOBBIN_SIZE ALTER COLUMN NAME SET NOT NULL;

ALTER TABLE BOBBIN_SIZE
ADD PRIMARY KEY (ID);

CREATE TABLE FLOSS
AS SELECT *
FROM CSVREAD('classpath:data/dmc.csv');

ALTER TABLE FLOSS ALTER COLUMN ID SET DATA TYPE BIGINT;
ALTER TABLE FLOSS ALTER COLUMN ID SET NOT NULL;
ALTER TABLE FLOSS ALTER COLUMN FLOSS_TYPE_ID SET DATA TYPE BIGINT;
ALTER TABLE FLOSS ALTER COLUMN FLOSS_TYPE_ID SET NOT NULL;
ALTER TABLE FLOSS ALTER COLUMN COLOR SET NOT NULL;

ALTER TABLE FLOSS
ADD PRIMARY KEY (ID);

ALTER TABLE FLOSS
    ADD CONSTRAINT floss_flosstype_id_const
    FOREIGN KEY (FLOSS_TYPE_ID) REFERENCES FLOSS_TYPE(ID);

CREATE TABLE BOBBIN
AS SELECT *
FROM CSVREAD('classpath:data/bobbins.csv');

ALTER TABLE BOBBIN ALTER COLUMN ID SET DATA TYPE BIGINT;
ALTER TABLE BOBBIN ALTER COLUMN ID SET NOT NULL;
ALTER TABLE BOBBIN ALTER COLUMN FLOSS_ID SET DATA TYPE BIGINT;
ALTER TABLE BOBBIN ALTER COLUMN FLOSS_ID SET NOT NULL;
ALTER TABLE BOBBIN ALTER COLUMN ORIGINAL SET DATA TYPE BOOLEAN;
ALTER TABLE BOBBIN ALTER COLUMN ORIGINAL SET NOT NULL;
ALTER TABLE BOBBIN ALTER COLUMN BOBBIN_SIZE_ID SET DATA TYPE BIGINT;
ALTER TABLE BOBBIN ALTER COLUMN BOBBIN_SIZE_ID SET NOT NULL;

ALTER TABLE BOBBIN
ADD PRIMARY KEY (ID);

ALTER TABLE BOBBIN
    ADD CONSTRAINT bobbin_floss_id_const
    FOREIGN KEY (FLOSS_ID) REFERENCES FLOSS(ID);

ALTER TABLE BOBBIN
    ADD CONSTRAINT bobbin_size_id_const
    FOREIGN KEY (BOBBIN_SIZE_ID) REFERENCES BOBBIN_SIZE(ID);
