CREATE TABLE FLOSS_TYPE
AS SELECT *
FROM CSVREAD('classpath:data/flossTypes.csv');

CREATE TABLE FLOSS
AS SELECT *
FROM CSVREAD('classpath:data/dmc.csv');

ALTER TABLE FLOSS_TYPE ALTER COLUMN ID SET DATA TYPE BIGINT;
ALTER TABLE FLOSS_TYPE ALTER COLUMN ID SET NOT NULL;
ALTER TABLE FLOSS_TYPE ALTER COLUMN NAME SET NOT NULL;

ALTER TABLE FLOSS_TYPE
ADD PRIMARY KEY (ID);

ALTER TABLE FLOSS ALTER COLUMN ID SET DATA TYPE BIGINT;
ALTER TABLE FLOSS ALTER COLUMN ID SET NOT NULL;
ALTER TABLE FLOSS ALTER COLUMN FLOSS_TYPE_ID SET DATA TYPE BIGINT;
ALTER TABLE FLOSS ALTER COLUMN FLOSS_TYPE_ID SET NOT NULL;
ALTER TABLE FLOSS ALTER COLUMN COLOR SET NOT NULL;

ALTER TABLE FLOSS
ADD PRIMARY KEY (ID);

ALTER TABLE FLOSS
    ADD CONSTRAINT floss_flosstype_id
    FOREIGN KEY (FLOSS_TYPE_ID) REFERENCES FLOSS_TYPE(ID);